services:
  db:
    container_name: db
    image: postgres:16.2
    environment:
      postgres_user: postgres
      postgres_PASSWORD: postgres
      postgres_db: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgressql/data

volumes:
  pgdata: {}
